name: CQ
favicon: null
layout_spectrum: 0.45388045092113316
typography_spectrum: 0.38831820571795106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.2759889967273921
  lightness: 0.12932914053089917
  saturation: 0.6837533854413778
  rhythmicContrast: 0.9820436362642795
purpose: []
